### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by k-kashapov** [alexpaniman/spotivar#1]
Prints "Welcome to spotivar" and does nothing. Please repair.
![2712a6ba206b5ec4f7ef974edbccacc1 1024_q6UyJ0c](https://user-images.githubusercontent.com/52855633/217844927-f426ce16-284a-4080-a283-e5d11aefed67.jpg)

**Comment by alexpaniman** [comment]
For now this **is** intended behavior! Star our repo and wait for future versions, hopefully it will do more than that soon enough :) We don't disappoint!

![spotivar2](https://user-images.githubusercontent.com/43866303/218212668-dd9cbb15-d2d5-4058-82b2-4b592b111bd6.png)
